version: "3.9"
services:
  web:
    container_name: back
    build: backend
    ports:
      - "8000:5000"
  front:
        image: "node:18-alpine"
        container_name: front
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./frontend:/home/node/app
        ports:
            - "3000:3000"
        command: sh -c 'npm install && npm ci && npm install nodemon && npm start'    